services:   
  redis:
    image: redis/redis-stack-server
    container_name: redis-server
    restart: unless-stopped
    ports:
      - 6379:6379
    environment:
      - REDIS_ARGS=--requirepass sameer_2005
    volumes:
      - redis-data:/data

volumes:
  redis-data:

